name: Deploy to GH Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Field Guide
      uses: actions/checkout@v3
      with:
        path: 'field-guide'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Query TFC Version
      id: version
      run: |
        output=$(python field-guide/src/versions.py)
        echo "::set-output name=version::$output"
    - name: Checkout TFC
      uses: actions/checkout@v3
      with:
        repository: 'TerraFirmaCraft/TerraFirmaCraft'
        ref: ${{ steps.version.outputs.version }}
        path: 'tfc'
    - name: Build
      run: |
        python field-guide/src/main.py tfc out
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
        clean: true
        single-commit: true